Repository StuPro-TOSCAna/cloudformation-builder, pull requests merged in 2018-03, with the labels that each got.

#32 Add basic Beanstalk implementation
  src/main/java/com/scaleset/cfbuilder/beanstalk/Application.java
  src/main/java/com/scaleset/cfbuilder/beanstalk/ApplicationResourceLifecycleConfig.java
  src/main/java/com/scaleset/cfbuilder/beanstalk/ApplicationVersion.java
  src/main/java/com/scaleset/cfbuilder/beanstalk/ConfigurationTemplate.java
  src/main/java/com/scaleset/cfbuilder/beanstalk/Environment.java
  src/main/java/com/scaleset/cfbuilder/beanstalk/EnvironmentTier.java
  src/main/java/com/scaleset/cfbuilder/beanstalk/OptionSetting.java
  src/main/java/com/scaleset/cfbuilder/beanstalk/SourceBundle.java
  src/main/java/com/scaleset/cfbuilder/beanstalk/SourceConfiguration.java
  src/test/java/com/scaleset/cfbuilder/CloudFormationBuilderTest.java
  src/test/java/com/scaleset/cfbuilder/TemplateTest.java
  src/test/java/com/scaleset/cfbuilder/beanstalk/BeanstalkTest.java
  src/test/java/com/scaleset/cfbuilder/core/FnTest.java
  src/test/java/com/scaleset/cfbuilder/core/ResourceProxyTest.java
  src/test/java/com/scaleset/cfbuilder/ec2/Ec2Test.java
  src/test/java/com/scaleset/cfbuilder/ec2/InstanceTest.java
  src/test/java/com/scaleset/cfbuilder/ec2/MetadataTest.java
  src/test/java/com/scaleset/cfbuilder/ec2/VolumeTest.java
Labels: enhancement, model extension

#35 Change optionSettings value to accept Object values
  src/main/java/com/scaleset/cfbuilder/beanstalk/OptionSetting.java
Labels: bugfix

#37 Update example in readme
  README.md
Labels: docs
